=== Smitt64/WorkFMT/qrsd/rsd/lib/debug/fmtxml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	    xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" elementFormDefault="qualified">

  <xsd:element name="TableList" id="d2e37">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Table" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Field" minOccurs="1" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="xsd:string">
                      <xsd:attribute name="T_NAME" id="d2e141" use="required">
                        <xsd:simpleType>
                          <xsd:restriction base="xsd:string">
                            <xsd:maxLength value="128"/>
                          </xsd:restriction>
                        </xsd:simpleType>
                      </xsd:attribute>
                      <xsd:attribute name="T_TYPE" id="d2e151" use="required">
                        <xsd:simpleType>
                          <xsd:restriction base="xsd:string">
                            <xsd:enumeration value="FT_BINARY" />
                            <xsd:enumeration value="FT_CHR" />
                            <xsd:enumeration value="FT_DATE" />
                            <xsd:enumeration value="FT_DECIMAL" />
                            <xsd:enumeration value="FT_DOUBLE" />
                            <xsd:enumeration value="FT_DOUBLEG" />
                            <xsd:enumeration value="FT_DOUBLEM" />
                            <xsd:enumeration value="FT_DOUBLER" />
                            <xsd:enumeration value="FT_FLOAT" />
                            <xsd:enumeration value="FT_FLOATG" />
                            <xsd:enumeration value="FT_INT16" />
                            <xsd:enumeration value="FT_INT32" />
                            <xsd:enumeration value="FT_INT64" />
                            <xsd:enumeration value="FT_LDMON" />
                            <xsd:enumeration value="FT_LDMONR" />
                            <xsd:enumeration value="FT_LDOUBLE" />
                            <xsd:enumeration value="FT_LMONEYR_OLD" />
                            <xsd:enumeration value="FT_LMONEY_OLD" />
                            <xsd:enumeration value="FT_MONEYR_OLD" />
                            <xsd:enumeration value="FT_MONEY_OLD" />
                            <xsd:enumeration value="FT_NUMERIC" />
                            <xsd:enumeration value="FT_NUMSTR" />
                            <xsd:enumeration value="FT_SHTM" />
                            <xsd:enumeration value="FT_SNR" />
                            <xsd:enumeration value="FT_STRING" />
                            <xsd:enumeration value="FT_TIME" />
                            <xsd:enumeration value="FT_UCHR" />
                          </xsd:restriction>
                        </xsd:simpleType>
                      </xsd:attribute>
                      <xsd:attribute name="T_SIZE" type="xsd:integer" id="d2e159" use="required" />
                      <xsd:attribute name="T_OUTLEN" type="xsd:integer" id="d2e169" use="required" />
                      <xsd:attribute name="T_DECPOINT" type="xsd:integer" id="d2e179" use="required" />
                      <xsd:attribute name="T_HIDDEN" type="xsd:boolean" id="d2e190" use="required" />
                      <xsd:attribute name="T_COMMENT" id="d2e198" use="required">
                        <xsd:simpleType>
                          <xsd:restriction base="xsd:string">
                            <xsd:maxLength value="128"/>
                          </xsd:restriction>
                        </xsd:simpleType>
                      </xsd:attribute>
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="Key" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="Segment" minOccurs="1" maxOccurs="unbounded">
                      <xsd:complexType>
                        <xsd:simpleContent>
                          <xsd:extension base="xsd:string">
                            <xsd:attribute name="T_FIELD" id="d2e286" use="required">
                              <xsd:simpleType>
                                <xsd:restriction base="xsd:string">
                                  <xsd:maxLength value="128"/>
                                </xsd:restriction>
                              </xsd:simpleType>
                            </xsd:attribute>
                            <xsd:attribute name="TF_ALTERNATE" type="xsd:boolean" id="d2e294" use="required" />
                            <xsd:attribute name="TF_DESCENDING" type="xsd:boolean" id="d2e302" use="required" />
                            <xsd:attribute name="TF_LOCAL" type="xsd:boolean" id="d2e310" use="required">
                            </xsd:attribute>
                            <xsd:attribute name="T_TYPE" id="d2e318" use="required">
                              <xsd:simpleType>
                                <xsd:restriction base="xsd:string">
                                  <xsd:enumeration value="Eautoinc" />
                                  <xsd:enumeration value="Ebfloat" />
                                  <xsd:enumeration value="Ecurrency" />
                                  <xsd:enumeration value="Edate" />
                                  <xsd:enumeration value="Edecimal" />
                                  <xsd:enumeration value="Efloat" />
                                  <xsd:enumeration value="Einteger" />
                                  <xsd:enumeration value="Elogical" />
                                  <xsd:enumeration value="Elstring" />
                                  <xsd:enumeration value="Emoney" />
                                  <xsd:enumeration value="Enumeric" />
                                  <xsd:enumeration value="Estring" />
                                  <xsd:enumeration value="Etime" />
                                  <xsd:enumeration value="Eunbin" />
                                  <xsd:enumeration value="Ezstring" />
                                </xsd:restriction>
                              </xsd:simpleType>
                            </xsd:attribute>
                            <xsd:attribute name="T_NULLVAL" type="xsd:integer" id="d2e327" use="required" />
                            <xsd:attribute name="T_ISREAL" type="xsd:boolean" id="d2e335" use="required">
                            </xsd:attribute>
                            <xsd:attribute name="T_COMMENT" id="d2e343" use="required">
                              <xsd:simpleType>
                                <xsd:restriction base="xsd:string">
                                  <xsd:maxLength value="128"/>
                                </xsd:restriction>
                              </xsd:simpleType>
                            </xsd:attribute>
                          </xsd:extension>
                        </xsd:simpleContent>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                  <xsd:attribute name="T_KEYNUM" type="xsd:integer" id="d2e213" use="required" />
                  <xsd:attribute name="TF_DUPLICATES" type="xsd:boolean" id="d2e223" use="required" />
                  <xsd:attribute name="TF_MODIFIABLE" type="xsd:boolean" id="d2e231" use="required" />
                  <xsd:attribute name="TF_BINARY" type="xsd:boolean" id="d2e239" use="required" />
                  <xsd:attribute name="TF_NULLVAL" type="xsd:boolean" id="d2e247" use="required" />
                  <xsd:attribute name="TF_SUPPLEMENT" type="xsd:boolean" id="d2e256" use="required" />
                  <xsd:attribute name="TF_EXTENDED" type="xsd:boolean"  id="d2e264" use="required" />
                  <xsd:attribute name="TF_MANUAL" type="xsd:boolean" id="d2e272" use="required" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="T_NAME" id="d2e50" use="required">
              <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="30"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:attribute>
            <xsd:attribute name="T_OWNER" id="d2e60" use="required">
              <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="9"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:attribute>
            <xsd:attribute name="T_CACHESIZE" type="xsd:integer" id="d2e70" use="required" />
            <xsd:attribute name="T_PKIDX" type="xsd:integer" id="d2e80" use="required" />
            <xsd:attribute name="T_BLOBTYPE" id="d2e90" use="required">
              <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                  <xsd:enumeration value="BT_BLOB_NO" />
                  <xsd:enumeration value="BT_BLOB_VAR" />
                  <xsd:enumeration value="BT_BLOB_STREAM" />
                  <xsd:enumeration value="BT_CLOB" />
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:attribute>
            <xsd:attribute name="T_BLOBLEN" type="xsd:integer" id="d2e99" use="required" />
            <xsd:attribute name="TF_TEMPORARY" type="xsd:boolean" id="d2e109" use="required" />
            <xsd:attribute name="TF_STRUCT" type="xsd:boolean" id="d2e117" use="required" />
            <xsd:attribute name="T_COMMENT" id="d2e125" use="required">
              <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                  <xsd:maxLength value="40"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:attribute>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== Smitt64/WorkFMT/RegparmTool/xml/dregval_dbt.xml
<?xml version="1.0" encoding="UTF-8"?>
<TableList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.softlab.ru fmtxml.xsd"
    xmlns="http://www.softlab.ru">
  <Table T_NAME="dregval_dbt" T_OWNER="" T_CACHESIZE="0" T_PKIDX="0" T_BLOBTYPE="BT_BLOB_VAR" T_BLOBLEN="2048" TF_TEMPORARY="false" TF_STRUCT="false" T_COMMENT="Значение настройки банка">
    <Field T_NAME="t_keyid" T_TYPE="FT_INT32" T_SIZE="4" T_OUTLEN="10" T_DECPOINT="0" T_HIDDEN="false" T_COMMENT="Идентификатор настройки"/>
    <Field T_NAME="t_regkind" T_TYPE="FT_INT32" T_SIZE="4" T_OUTLEN="0" T_DECPOINT="1" T_HIDDEN="false" T_COMMENT="Вид значения настройки"/>
    <Field T_NAME="t_objectid" T_TYPE="FT_INT32" T_SIZE="4" T_OUTLEN="4" T_DECPOINT="0" T_HIDDEN="false" T_COMMENT="Идентификатор объекта"/>
    <Field T_NAME="t_blockuservalue" T_TYPE="FT_CHR" T_SIZE="1" T_OUTLEN="1" T_DECPOINT="0" T_HIDDEN="false" T_COMMENT="Запрет действия пользовательских значений"/>
    <Field T_NAME="t_expdep" T_TYPE="FT_INT16" T_SIZE="2" T_OUTLEN="0" T_DECPOINT="0" T_HIDDEN="false" T_COMMENT="Порядок распространения по ТС"/>
    <Field T_NAME="t_lintvalue" T_TYPE="FT_INT32" T_SIZE="4" T_OUTLEN="10" T_DECPOINT="0" T_HIDDEN="false" T_COMMENT="Значение целого типа"/>
    <Field T_NAME="t_ldoublevalue" T_TYPE="FT_DOUBLE" T_SIZE="8" T_OUTLEN="10" T_DECPOINT="4" T_HIDDEN="false" T_COMMENT="Значение действительного типа"/>
    <Key T_KEYNUM="0" TF_DUPLICATES="false" TF_MODIFIABLE="true" TF_BINARY="false" TF_NULLVAL="false" TF_SUPPLEMENT="false" TF_EXTENDED="true" TF_MANUAL="false">
      <Segment T_FIELD="t_keyid" TF_ALTERNATE="false" TF_DESCENDING="false" TF_LOCAL="false" T_TYPE="Einteger" T_NULLVAL="0" T_ISREAL="true" T_COMMENT="Индекс &quot;Alternate Key1&quot; (&quot;XAK1_DREGVAL_DBT&quot;). (#00)"/>
      <Segment T_FIELD="t_regkind" TF_ALTERNATE="false" TF_DESCENDING="false" TF_LOCAL="false" T_TYPE="Einteger" T_NULLVAL="0" T_ISREAL="true" T_COMMENT="Индекс &quot;Alternate Key1&quot; (&quot;XAK1_DREGVAL_DBT&quot;). (#01)"/>
      <Segment T_FIELD="t_objectid" TF_ALTERNATE="false" TF_DESCENDING="false" TF_LOCAL="false" T_TYPE="Einteger" T_NULLVAL="0" T_ISREAL="true" T_COMMENT="Индекс &quot;Alternate Key1&quot; (&quot;XAK1_DREGVAL_DBT&quot;). (#02)"/>
    </Key>
    <Key T_KEYNUM="1" TF_DUPLICATES="true" TF_MODIFIABLE="true" TF_BINARY="false" TF_NULLVAL="false" TF_SUPPLEMENT="false" TF_EXTENDED="true" TF_MANUAL="false">
      <Segment T_FIELD="t_regkind" TF_ALTERNATE="false" TF_DESCENDING="false" TF_LOCAL="false" T_TYPE="Einteger" T_NULLVAL="0" T_ISREAL="true" T_COMMENT=" (#00)"/>
      <Segment T_FIELD="t_objectid" TF_ALTERNATE="false" TF_DESCENDING="false" TF_LOCAL="false" T_TYPE="Einteger" T_NULLVAL="0" T_ISREAL="true" T_COMMENT=" (#01)"/>
    </Key>
  </Table>
</TableList>
